// mf-b/src/components/ItemForm.tsx
import { useState, FormEvent, ChangeEvent } from 'react';

interface ItemFormProps {
  onItemAdded: () => void;
  createItem: (name: string) => void;
}

export default function ItemForm({ onItemAdded, createItem }: ItemFormProps) {
  const [name, setName] = useState('');
  const [error, setError] = useState('');

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();
    if (!name.trim()) {
      setError('Name is required');
      return;
    }
    if (name.length > 50) {
      setError('Name must be 50 characters or less');
      return;
    }

    try {
      createItem(name);
      setName('');
      setError('');
      onItemAdded();
    } catch (err: any) {
      setError(err.message);
    }
  };

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    setName(e.target.value);
    if (error) setError('');
  };

  return (
    <div style={{ marginBottom: '20px', padding: '15px', backgroundColor: '#fff', borderRadius: '8px', boxShadow: '0 2px 4px rgba(0,0,0,0.1)' }}>
      <h3 style={{ marginTop: 0, color: '#333' }}>Create New Item</h3>
      <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
        <div>
          <input
            type="text"
            value={name}
            onChange={handleChange}
            placeholder="Enter item name..."
            style={{ padding: '8px', width: '100%', maxWidth: '300px', borderRadius: '4px', border: '1px solid #ccc' }}
          />
        </div>
        {error && <div style={{ color: 'red', fontSize: '14px' }}>{error}</div>}
        <div>
          <button type="submit" style={{ padding: '8px 16px', backgroundColor: '#007bff', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>
            Add Item
          </button>
        </div>
      </form>
    </div>
  );
}

// mf-c/src/components/ItemForm.vue
<template>
  <div>
    <h2>Add New Item</h2>
    <form @submit.prevent="submitForm">
      <div>
        <label for="name">Name:</label>
        <input id="name" v-model="name" type="text" maxlength="50" required />
      </div>
      <button type="submit">Add</button>
    </form>
    <p v-if="error" class="error">{{ error }}</p>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import { itemService } from '../services/ItemService';

export default defineComponent({
  name: 'ItemForm',
  emits: ['item-added'],
  setup(props, { emit }) {
    const name = ref('');
    const error = ref('');

    const submitForm = () => {
      error.value = '';
      if (!name.value.trim()) {
        error.value = 'Name is required';
        return;
      }
      if (name.value.length > 50) {
        error.value = 'Name must be 50 characters or less';
        return;
      }

      try {
        itemService.createItem(name.value.trim());
        name.value = '';
        emit('item-added');
      } catch (e: any) {
        error.value = e.message || 'An error occurred';
      }
    };

    return {
      name,
      error,
      submitForm
    };
  }
});
</script>

<style scoped>
.error {
  color: red;
}
form {
  margin-bottom: 20px;
}
label {
  margin-right: 10px;
}
button {
  margin-left: 10px;
  background-color: #41b883;
  color: white;
  border: none;
  padding: 5px 15px;
  cursor: pointer;
}
button:hover {
  background-color: #42b983;
}
</style>
